// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	domain "github.com/dzrry/dzurl/domain"
	mock "github.com/stretchr/testify/mock"
)

// RedirectRepo is an autogenerated mock type for the RedirectRepo type
type RedirectRepo struct {
	mock.Mock
}

// Load provides a mock function with given fields: key
func (_m *RedirectRepo) Load(key string) (*domain.Redirect, error) {
	ret := _m.Called(key)

	var r0 *domain.Redirect
	if rf, ok := ret.Get(0).(func(string) *domain.Redirect); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Redirect)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: redirect
func (_m *RedirectRepo) Store(redirect *domain.Redirect) error {
	ret := _m.Called(redirect)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Redirect) error); ok {
		r0 = rf(redirect)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
