// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// RedirectHandler is an autogenerated mock type for the RedirectHandler type
type RedirectHandler struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *RedirectHandler) Get(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// Post provides a mock function with given fields: _a0, _a1
func (_m *RedirectHandler) Post(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}
